# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "custom-attributes"
  s.version = "0.2.26"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthijs Groen"]
  s.date = "2011-10-03"
  s.description = "Easy management of extra model attributes. Can store fields in the model if provided"
  s.email = "matthijs.groen@gmail.com"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "generators/has_custom_attributes_migration/has_custom_attributes_migration_generator.rb",
    "generators/has_custom_attributes_migration/templates/migration.rb",
    "lib/active_record/custom_attributes.rb",
    "lib/active_record/custom_attributes/custom_attribute.rb",
    "lib/active_record/custom_attributes/custom_attribute_list.rb",
    "lib/active_record/custom_attributes/custom_attribute_model.rb",
    "lib/custom-attributes.rb",
    "lib/formtastic/custom_attributes.rb",
    "lib/generators/custom_attributes/migration/migration_generator.rb",
    "lib/generators/custom_attributes/migration/templates/active_record/migration.rb",
    "rails/init.rb",
    "spec/custom_attributes/has_custom_attributes_spec.rb",
    "spec/database.yml.sample",
    "spec/models.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/matthijsgroen/custom-attributes"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Management for custom model attributes."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.0"])
      s.add_runtime_dependency(%q<rspec>, ["~> 2.0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

